apiVersion: gemfire.tanzu.vmware.com/v1
kind: GemFireCluster
metadata:
  name: tanzu-gemfire
  namespace: gemfire-cluster
spec:
  image: registry.pivotal.io/tanzu-gemfire-for-kubernetes/gemfire-k8s:1.0.0
  locators:
    replicas: 3 #default is 1
  servers:
    replicas: 4 #default is 2
